#!/usr/bin/python
SHAREDIR="/usr/share/enemies-of-carlotta"

import sys
sys.path.insert(0, SHAREDIR)

import eoc, os

EOC_DOTDIR = os.environ.get('EOC_DOTDIR', None)
if EOC_DOTDIR is not None:
    eoc.DOTDIR=EOC_DOTDIR
eoc.main(sys.argv[1:])
